# Generated by Django 5.2.4 on 2025-08-07 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 7, 17, 30, 10, 857915, tzinfo=datetime.timezone.utc)),
        ),
    ]
